version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iyikatrace
    ports:
      - "5432:5432"
volumes:
  postgres_data:
    volumes:
      - postgres_data:/var/lib/postgresql/data
